export enum API_TYPE {
  MASTER = 'master',
  CONFIG = 'config',
  TRANSACTIONAL = 'transactional',
}

export enum API_STATUS {
  SUCCESS = 'success',
  FAILED = 'failed',
  INITIAL = 'initial',
  PENDING = 'pending',
  NO_CONTENT = 'no content',
}

export enum API_RESPONSIBILITY {
  GET_ITEMS = 'GET_ITEMS',
  GET_SERIALS_TABLE_TYPE = 'GET_SERIALS_TABLE_TYPE',
  GET_SUBINVENTORIES = 'GET_SUBINVENTORIES',
  GET_LOCATORS = 'GET_LOCATORS',
  GET_GL_PERIODS = 'GET_GL_PERIODS',
  GET_DOCUMENTS_FOR_RECEIVING = 'GET_DOCUMENTS_FOR_RECEIVING',
  GET_LOTS_TABLE_TYPE = 'GET_LOTS_TABLE_TYPE',
  GET_ON_HAND_TABLE_TYPE = 'GET_ON_HAND_TABLE_TYPE',
  GET_INVENTORY_PERIODS = 'GET_INVENTORY_PERIODS',
  GET_LOCATIONS = 'GET_LOCATION',
  GET_ON_HAND_WMS_FILTER_TABLE = 'GET_ON_HAND_WMS_FILTER_TABLE',
}
